update - standardize path usage

diff --git a/App/latex-app/Dockerfile b/App/latex-app/Dockerfile
--- a/App/latex-app/Dockerfile
+++ b/App/latex-app/Dockerfile
@@ -1,10 +1,10 @@
-# Use the base LaTeX image
-FROM texlive/texlive:latest
+# Use the smaller TeXLive image
+FROM texlive/texlive:latest-small
 
 # Set a working directory within the container
 WORKDIR /app
 
-# Install inotify-tools for monitoring file changes
+# Install necessary tools
 RUN apt-get update && \
     apt-get install -y inotify-tools apt-transport-https ca-certificates gnupg curl sudo && \
     rm -rf /var/lib/apt/lists/*
@@ -19,6 +19,16 @@ RUN apt-get update
 
 # Update and install the Cloud SDK. For Local clusters ONLY
 RUN apt-get install -y google-cloud-cli
+
+# Copy required_packages.txt into the container
+COPY required_packages.txt /app/
+
+# Install LaTeX packages from required_packages.txt
+RUN tlmgr update --self && \
+    cat required_packages.txt | while read package; do \
+        tlmgr install $package || echo "Failed to install package: $package"; \
+    done && \
+    tlmgr path add
 
 # Copy the entrypoint script into the container
 COPY entrypoint_final.sh /app/
